name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [DEBUG, RELEASE]
    env:
      TARGET: ${{ matrix.target }}

    steps:
    - uses: actions/checkout@v3
    - name: Install libs
      run: sudo apt update && sudo apt install libjson-c-dev libcurl4-openssl-dev
    - name: Build
      run: make all
    - name: Run tests
      run: make check
